[build]
builder = "nixpacks"
buildCommand = "npm run prisma:generate && npm run build"

[deploy]
startCommand = "npm run prisma:migrate deploy && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
